services:
  rac-frontend:
    build: .
    container_name: rac-frontend
    command: reflex run --env prod
    expose:
      - "3000"
      - "8000"
    restart: always
    environment:
      - BACKEND_URL=http://rac-backend:8001
      - API_URL=https://rsfsecure.site
    volumes:
      - ./.env:/var/www/ciberapp/RAC-ProyectoIA/.env
    networks:
      - rac-network
      - red-proxy

  rac-backend:
    build: .
    container_name: rac-backend
    command: uvicorn backend:api --host 0.0.0.0 --port 8001
    expose:
      - "8001"
    restart: always
    volumes:
      - ./.env:/var/www/ciberapp/RAC-ProyectoIA/.env
    networks:
      - rac-network

networks:
  rac-network:
    driver: bridge

  red-proxy:
    external: true